version: '3.8'

services:
  chat:
    image: ${DOCKER_IMAGE_URL}
    container_name: factory-chatbot-chat
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=chat
      - AWS_REGION=${AWS_REGION:-us-west-2}